### ISSUE TITLE
Cant open Chromium-Browser

### ISSUE THREAD

**Issue by Pulse-Git** [csiew/BiscuitWM#5]
Im new to Biscuit and i am currently trying to open an browser
if run "chromium-browser" in the deskbar nothing is happening

anythin that i need to do?

my start script:
`
#!/bin/bash

OLDDISPLAY=$DISPLAY
killall Xephyr  &>/dev/null
export DISPLAY=:1
Xephyr -screen $1 -br :1 &
export DISPLAY=:0
python3 main.py
pkill Xephyr  &>/dev/null
export "DISPLAY=$OLDDISPLAY"

`

**Comment by csiew** [comment]
This appears to have been caused by a sneaky leading/prefix space character at the start of the text being entered in the launcher. I've just pushed a fix that strips this leading space character for now.

Bug fix commit: https://github.com/csiew/BiscuitWM/commit/b2e05aa3775fcec257262b15c55b9cc6594b526e

**Comment by Pulse-Git** [comment]
@csiew 
Sorry for the late reply
Im aware of that issue, but i still get no window if i execute the command when i remove the leading white space
